// Tests/CoreChecks/BcryptPBKDFChecks.swift
//
// Known-answer tests for the OpenSSH/OpenBSD `bcrypt_pbkdf` KDF and its inner EksBlowfish
// `bcrypt_hash`. Security-sensitive crypto ships only with passing KATs, so this asserts exact
// output bytes against the published OpenBSD reference vectors.
//
// KAT source: the OpenBSD `bcrypt_pbkdf` reference test vectors, as embedded verbatim in the Go
// standard library's `golang.org/x/crypto/ssh/internal/bcrypt_pbkdf` test suite
// (`bcrypt_pbkdf_test.go`), whose comment reads "Test vectors generated by the reference
// implementation from OpenBSD." Both the outer `Key`/`bcrypt_pbkdf` vectors and the inner
// `bcryptHash`/`bcrypt_hash` vector are checked.
import Foundation
import SimpletonSFTP

func runBcryptPBKDFChecks(_ t: TestRunner) {
    runBcryptHashKAT(t)
    runBcryptPBKDFKAT(t)
    runOpenSSHCipherSanity(t)
}

/// The inner EksBlowfish hash vector: `pass[i] = i`, `salt[i] = i + 64` (both 64 bytes, the SHA-512
/// digest length that `bcrypt_pbkdf` feeds it), producing a fixed 32-byte output.
private func runBcryptHashKAT(_ t: TestRunner) {
    t.suite("bcrypt_hash matches the OpenBSD reference vector") {
        let pass = (0..<64).map { UInt8($0) }
        let salt = (0..<64).map { UInt8($0 + 64) }
        let expected: [UInt8] = [
            0x87, 0x90, 0x48, 0x70, 0xee, 0xf9, 0xde, 0xdd, 0xf8, 0xe7,
            0x61, 0x1a, 0x14, 0x01, 0x06, 0xe6, 0xaa, 0xf1, 0xa3, 0x63,
            0xd9, 0xa2, 0xc5, 0x04, 0xdb, 0x35, 0x64, 0x43, 0x72, 0x1e,
            0xb5, 0x55,
        ]
        let actual = BcryptPBKDF.bcryptHash(sha2pass: pass, sha2salt: salt)
        t.expectEqual(actual, expected, "bcrypt_hash(0..63, 64..127)")
    }
}

/// The three published `bcrypt_pbkdf` golden vectors: ASCII, embedded-NUL, and a UTF-8 (Cyrillic)
/// case that also exercises a >32-byte key length (87 bytes) and thus the multi-block scatter loop.
private func runBcryptPBKDFKAT(_ t: TestRunner) {
    t.suite("bcrypt_pbkdf matches the OpenBSD reference vectors") {
        expectKAT(
            t, password: "password", salt: "salt", rounds: 12,
            expected: [
                0x1a, 0xe4, 0x2c, 0x05, 0xd4, 0x87, 0xbc, 0x02, 0xf6,
                0x49, 0x21, 0xa4, 0xeb, 0xe4, 0xea, 0x93, 0xbc, 0xac,
                0xfe, 0x13, 0x5f, 0xda, 0x99, 0x97, 0x4c, 0x06, 0xb7,
                0xb0, 0x1f, 0xae, 0x14, 0x9a,
            ],
            label: "(\"password\", \"salt\", 12)")

        expectKAT(
            t, password: "passwordy\u{0}PASSWORD\u{0}", salt: "salty\u{0}SALT\u{0}", rounds: 3,
            expected: [
                0x7f, 0x31, 0x0b, 0xd3, 0xe7, 0x8c, 0x32, 0x80, 0xc5,
                0x9c, 0xe4, 0x59, 0x52, 0x11, 0xa2, 0x92, 0x8e, 0x8d,
                0x4e, 0xc7, 0x44, 0xc1, 0xed, 0x2e, 0xfc, 0x9f, 0x76,
                0x4e, 0x33, 0x88, 0xe0, 0xad,
            ],
            label: "(embedded-NUL, 3)")

        expectKAT(
            t, password: "секретное слово", salt: "посолить немножко", rounds: 8,
            expected: [
                0x8d, 0xf4, 0x3f, 0xc6, 0xfe, 0x13, 0x1f, 0xc4, 0x7f,
                0x0c, 0x9e, 0x39, 0x22, 0x4b, 0xd9, 0x4c, 0x70, 0xb6,
                0xfc, 0xc8, 0xee, 0x81, 0x35, 0xfa, 0xdd, 0xf6, 0x11,
                0x56, 0xe6, 0xcb, 0x27, 0x33, 0xea, 0x76, 0x5f, 0x31,
                0x5a, 0x3e, 0x1e, 0x4a, 0xfc, 0x35, 0xbf, 0x86, 0x87,
                0xd1, 0x89, 0x25, 0x4c, 0x1e, 0x05, 0xa6, 0xfe, 0x80,
                0xc0, 0x61, 0x7f, 0x91, 0x83, 0xd6, 0x72, 0x60, 0xd6,
                0xa1, 0x15, 0xc6, 0xc9, 0x4e, 0x36, 0x03, 0xe2, 0x30,
                0x3f, 0xbb, 0x43, 0xa7, 0x6a, 0x64, 0x52, 0x3f, 0xfd,
                0xa6, 0x86, 0xb1, 0xd4, 0x51, 0x85, 0x43,
            ],
            label: "(Cyrillic UTF-8, 8, 87-byte key)")
    }
}

/// A cipher round-trip sanity check: AES-CTR is symmetric, so decrypting a value we produced by
/// CTR-"decrypting" zeros twice returns to zeros — this proves the CommonCrypto CTR wiring and IV
/// handling are wired correctly (the exact bytes are further pinned by the end-to-end key fixtures).
private func runOpenSSHCipherSanity(_ t: TestRunner) {
    t.suite("OpenSSHCipher AES-CTR is an involution on the keystream") {
        let key = [UInt8](repeating: 0x2a, count: 32)
        let iv = [UInt8](repeating: 0x11, count: 16)
        let plaintext = (0..<48).map { UInt8($0 & 0xff) }
        do {
            let cipher = OpenSSHCipher.aes256ctr
            let once = try cipher.decrypt(plaintext, key: key, iv: iv)
            let twice = try cipher.decrypt(once, key: key, iv: iv)
            t.expectEqual(twice, plaintext, "CTR(CTR(x)) == x")
            t.expect(once != plaintext, "CTR actually transforms the input")
        } catch {
            t.expect(false, "AES-CTR round-trip threw: \(error)")
        }
    }
}

// MARK: - Helpers

private func expectKAT(
    _ t: TestRunner, password: String, salt: String, rounds: Int, expected: [UInt8], label: String
) {
    do {
        let actual = try BcryptPBKDF.derive(
            password: Array(password.utf8), salt: Array(salt.utf8), keyLen: expected.count,
            rounds: rounds)
        t.expectEqual(actual, expected, "bcrypt_pbkdf \(label)")
    } catch {
        t.expect(false, "bcrypt_pbkdf \(label) threw: \(error)")
    }
}
